package tuckersoft.bandersnatch.service;
import jakarta.mail.internet.MimeMessage; import tuckersoft.bandersnatch.event.DecisionCommittedEvent; import tuckersoft.bandersnatch.model.*; import tuckersoft.bandersnatch.repo.*; import org.slf4j.*; import org.springframework.mail.javamail.*; import org.springframework.scheduling.annotation.Async; import org.springframework.stereotype.Component; import org.springframework.transaction.annotation.*; import org.springframework.transaction.event.*; import java.time.Instant;
@Component public class BranchNotificationListener {
 private static final Logger log=LoggerFactory.getLogger(BranchNotificationListener.class);
 private final DecisionRepository decisions; private final RealityLogRepository logs; private final PlaythroughRepository plays; private final JavaMailSender mail;
 public BranchNotificationListener(DecisionRepository d,RealityLogRepository l,PlaythroughRepository p,JavaMailSender m){decisions=d;logs=l;plays=p;mail=m;}
 @Async("branchExecutor") @Transactional(propagation=Propagation.REQUIRES_NEW) @TransactionalEventListener(phase=TransactionPhase.AFTER_COMMIT)
 public void alCommit(DecisionCommittedEvent e){Decision d=decisions.findById(e.decisionId()).orElse(null);if(d==null)return;d.setStatus("PROCESANDO");d.setUpdatedAt(Instant.now());decisions.save(d);
  String subject="[TUCKERSOFT] "+e.branchType()+" en "+e.playerTag()+" | Impacto "+e.impactLevel();
  try{if(e.simulateMailFailure())throw new RuntimeException("SMTP failure simulated by QA");MimeMessage msg=mail.createMimeMessage();MimeMessageHelper h=new MimeMessageHelper(msg,false);h.setTo(e.recipientEmail());h.setSubject(subject);h.setText(body(e),false);mail.send(msg);
   d.setStatus("ESTABILIZADA");d.setUpdatedAt(Instant.now());decisions.save(d);RealityLog r=base(d,e,subject);r.setLogStatus("SENT");r.setSentAt(Instant.now());logs.save(r);
  }catch(Exception ex){d.setStatus("ERROR");d.setUpdatedAt(Instant.now());decisions.save(d);RealityLog r=base(d,e,subject);r.setLogStatus("FAILED");r.setErrorMessage(ex.getMessage());logs.save(r);log.error("[BRANCH-LOG] Decision ID: {} | Player: {} | Branch: {} | Impact: {} | Unit: {} | Node: {} -> {} | Thread: {} | Status: {}",d.getId(),e.playerTag(),e.branchType(),e.impactLevel(),e.handlerUnit(),e.sourceNodeCode(),e.resolvedNodeCode(),Thread.currentThread().getName(),d.getStatus(),ex);}
  log.info("[BRANCH-LOG] Decision ID: {} | Player: {} | Branch: {} | Impact: {} | Unit: {} | Node: {} -> {} | Thread: {} | Status: {}",d.getId(),e.playerTag(),e.branchType(),e.impactLevel(),e.handlerUnit(),e.sourceNodeCode(),e.resolvedNodeCode(),Thread.currentThread().getName(),d.getStatus());
 }
 private RealityLog base(Decision d,DecisionCommittedEvent e,String s){RealityLog r=new RealityLog();r.setDecision(d);r.setRecipientEmail(e.recipientEmail());r.setSubject(s);r.setCreatedAt(Instant.now());return r;}
 private String body(DecisionCommittedEvent e){return "Hola "+e.displayName()+",\n\nUna partida de prueba acaba de ramificarse.\n\n"+
 "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\nDecision ID      : #"+e.decisionId()+"\nJugador          : "+e.playerTag()+"\nRama             : "+e.branchType()+"\nImpacto          : "+e.impactLevel()+"\nDepartamento     : "+e.handlerUnit()+"\nConsecuencia     : "+e.outcomeCode()+"\nNodo origen      : "+e.sourceNodeCode()+"\nNodo destino     : "+(e.resolvedNodeCode()==null?"-":e.resolvedNodeCode())+"\nEstado partida   : "+e.playthroughStatus()+"\nLucidez          : "+e.lucidity()+"/100\nNivel de control : "+e.controlLevel()+"/100\nFinal            : "+(e.endingCode()==null?"-":e.endingCode())+"\nRegistrada       : "+Instant.now()+"\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\nDecisión original del jugador:\n\""+e.rawInput()+"\"\n\n— Tuckersoft Branch Engine, 1984";}
}
