package tuckersoft.bandersnatch.service;
import tuckersoft.bandersnatch.dto.DTOs; import tuckersoft.bandersnatch.error.ApiException; import tuckersoft.bandersnatch.event.DecisionCommittedEvent; import tuckersoft.bandersnatch.model.*; import tuckersoft.bandersnatch.repo.*; import org.springframework.context.ApplicationEventPublisher; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.text.Normalizer; import java.time.Instant; import java.util.*;
@Service public class DecisionService {
 private final DecisionRepository decisions; private final PlaythroughRepository plays; private final StoryNodeRepository nodes; private final UserService users; private final ApplicationEventPublisher publisher;
 public DecisionService(DecisionRepository d,PlaythroughRepository p,StoryNodeRepository n,UserService u,ApplicationEventPublisher ap){decisions=d;plays=p;nodes=n;users=u;publisher=ap;}
 public String classify(String raw){String t=Normalizer.normalize(raw,Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase(Locale.ROOT);if(t.chars().noneMatch(c->c>='a'&&c<='z'))return "ENTRADA_CORRUPTA";if(t.contains("netflix")||t.contains("camara")||t.contains("espectador")||t.contains("videojuego"))return "RUPTURA_CUARTA_PARED";if(t.contains("vigilan")||t.contains("simbolo")||t.contains("conspiracion"))return "SOSPECHA";if(t.contains("rechaza")||t.contains("destruye")||t.contains("desobedece")||t.contains("renuncia"))return "REBELDIA";return "OBEDIENCIA";}
 private String[] deriv(String b){return switch(b){case "OBEDIENCIA"->new String[]{"Mesa de Guion","ADVANCE_MAIN_PATH"};case "REBELDIA"->new String[]{"Control de Continuidad","FORK_TIMELINE"};case "SOSPECHA"->new String[]{"Oficina de Seguridad","INJECT_WHITE_BEAR_SYMBOL"};case "RUPTURA_CUARTA_PARED"->new String[]{"Departamento Netflix","BREAK_FOURTH_WALL"};default->new String[]{"Archivo de Errores","DISCARD_INPUT"};};}
 private int[] delta(String i){return switch(i){case "LEVE"->new int[]{-5,5};case "MODERADO"->new int[]{-15,10};case "GRAVE"->new int[]{-30,20};case "CRITICO"->new int[]{-40,45};default->throw new ApiException(400,"INVALID_IMPACT","Impacto inválido");};}
 @Transactional public DTOs.DecisionResponse decide(DTOs.DecisionRequest r,boolean simulate){Playthrough p=plays.findById(r.playthroughId()).orElseThrow(()->new ApiException(404,"PLAYTHROUGH_NOT_FOUND","Partida no encontrada"));User u=users.current();if(!p.getUser().getId().equals(u.getId()))throw new ApiException(403,"FORBIDDEN","No puedes decidir sobre esta partida");if(!"ACTIVA".equals(p.getStatus()))throw new ApiException(409,"PLAYTHROUGH_FINISHED","La partida ya finalizó");
  String branch=classify(r.rawInput());String[] d=deriv(branch);StoryNode source=p.getCurrentNode();Decision x=new Decision();x.setPlaythrough(p);x.setNode(source);x.setRawInput(r.rawInput());x.setBranchType(branch);x.setImpactLevel(r.impactLevel());x.setHandlerUnit(d[0]);x.setOutcomeCode(d[1]);x.setCreatedAt(Instant.now());x.setUpdatedAt(x.getCreatedAt());
  if("ENTRADA_CORRUPTA".equals(branch)){x.setResolvedNodeCode(null);x.setStatus("ERROR");Decision saved=decisions.save(x);return dto(saved);}
  int[] dd=delta(r.impactLevel());p.setLucidity(Math.max(0,p.getLucidity()+dd[0]));p.setControlLevel(Math.min(100,p.getControlLevel()+dd[1]));
  String dest=("RUPTURA_CUARTA_PARED".equals(branch)||"CRITICO".equals(r.impactLevel()))?source.getGlitchBranchCode():source.getPrimaryBranchCode();x.setResolvedNodeCode(dest);
  StoryNode target=dest==null?null:nodes.findByNodeCode(dest).orElse(null);
  if(p.getControlLevel()>=100){p.setStatus("FINALIZADA");p.setEndingCode("ENDING_PAC_SYMBOL");}
  else if(p.getLucidity()<=0){p.setStatus("FINALIZADA");p.setEndingCode("ENDING_WHITE_BEAR");}
  else if(target==null){p.setStatus("FINALIZADA");p.setEndingCode("ENDING_NETFLIX_CUT");}
  else {p.setCurrentNode(target);}
  p.setUpdatedAt(Instant.now());plays.save(p);x.setStatus("REGISTRADA");Decision saved=decisions.save(x);
  publisher.publishEvent(new DecisionCommittedEvent(saved.getId(),u.getEmail(),u.getDisplayName(),p.getPlayerTag(),branch,r.impactLevel(),d[0],d[1],source.getNodeCode(),dest,p.getStatus(),p.getLucidity(),p.getControlLevel(),p.getEndingCode(),r.rawInput(),simulate));
  return dto(saved);
 }
 public DTOs.DecisionResponse get(long id){Decision d=decisions.findById(id).orElseThrow(()->new ApiException(404,"DECISION_NOT_FOUND","Decisión no encontrada"));authorizeRead(d);return dto(d);}
 public List<DTOs.RealityLogResponse> logs(long id,RealityLogRepository logs){Decision d=decisions.findById(id).orElseThrow(()->new ApiException(404,"DECISION_NOT_FOUND","Decisión no encontrada"));authorizeRead(d);return logs.findByDecisionOrderByCreatedAtAsc(d).stream().map(x->new DTOs.RealityLogResponse(x.getId(),d.getId(),x.getRecipientEmail(),x.getSubject(),x.getLogStatus(),x.getErrorMessage(),x.getSentAt(),x.getCreatedAt())).toList();}
 public Page<Decision> searchRaw(String branch,String impact,String status,Long pid,int page,int size){User u=users.current();return decisions.search(u.getId(),branch,impact,status,pid,PageRequest.of(Math.max(0,page),size,Sort.by(Sort.Direction.DESC,"createdAt")));}
 private void authorizeRead(Decision d){User u=users.current();if(!d.getPlaythrough().getUser().getId().equals(u.getId())&&!"ROLE_ADMIN".equals(u.getRole()))throw new ApiException(403,"FORBIDDEN","No tienes acceso a esta decisión");}
 public DTOs.DecisionResponse dto(Decision d){Playthrough p=d.getPlaythrough();return new DTOs.DecisionResponse(d.getId(),p.getId(),p.getPlayerTag(),d.getNode().getNodeCode(),d.getResolvedNodeCode(),d.getRawInput(),d.getBranchType(),d.getImpactLevel(),d.getHandlerUnit(),d.getOutcomeCode(),d.getStatus(),p.getStatus(),p.getLucidity(),p.getControlLevel(),p.getEndingCode(),d.getCreatedAt(),d.getUpdatedAt());}
}
