package tuckersoft.bandersnatch.service;
import tuckersoft.bandersnatch.dto.DTOs; import tuckersoft.bandersnatch.error.ApiException; import tuckersoft.bandersnatch.model.*; import tuckersoft.bandersnatch.repo.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.Instant; import java.util.*;
@Service public class PlaythroughService {
 private final PlaythroughRepository plays; private final StoryNodeRepository nodes; private final UserService users; private final DecisionRepository decisions;
 public PlaythroughService(PlaythroughRepository p,StoryNodeRepository n,UserService u,DecisionRepository d){plays=p;nodes=n;users=u;decisions=d;}
 @Transactional public DTOs.PlaythroughResponse create(DTOs.PlaythroughRequest r){User u=users.current();StoryNode n=nodes.findByNodeCode(r.startNodeCode()).orElseThrow(()->new ApiException(404,"NODE_NOT_FOUND","Nodo no encontrado"));if(plays.existsByPlayerTag(r.playerTag()))throw new ApiException(409,"PLAYTHROUGH_EXISTS","playerTag ya existe");if(n.getBranchCapacity()>0 && n.getCurrentBranches()>=n.getBranchCapacity())throw new ApiException(400,"NODE_FULL","El nodo está lleno");Playthrough p=new Playthrough();p.setPlayerTag(r.playerTag());p.setUser(u);p.setStartNodeCode(n.getNodeCode());p.setCurrentNode(n);p.setLucidity(100);p.setControlLevel(0);p.setStatus("ACTIVA");p.setCreatedAt(Instant.now());p.setUpdatedAt(p.getCreatedAt());n.setCurrentBranches(n.getCurrentBranches()+1);nodes.save(n);return dto(plays.save(p));}
 public List<DTOs.PlaythroughResponse> list(){User u=users.current();List<Playthrough> x="ROLE_ADMIN".equals(u.getRole())?plays.findAllByOrderByCreatedAtDesc():plays.findByUserOrderByCreatedAtDesc(u);return x.stream().map(this::dto).toList();}
 public Playthrough getOwnedOrAdmin(long id,boolean write){Playthrough p=plays.findById(id).orElseThrow(()->new ApiException(404,"PLAYTHROUGH_NOT_FOUND","Partida no encontrada"));User u=users.current();if(!p.getUser().getId().equals(u.getId()) && (!"ROLE_ADMIN".equals(u.getRole())||write))throw new ApiException(403,"FORBIDDEN","No tienes acceso a esta partida");return p;}
 public DTOs.PlaythroughResponse get(long id){return dto(getOwnedOrAdmin(id,false));}
 public DTOs.PathResponse path(long id){Playthrough p=getOwnedOrAdmin(id,false);List<DTOs.PathStep> steps=new ArrayList<>();int i=1;for(Decision d:decisions.findByPlaythroughOrderByCreatedAtAsc(p)){if(d.getResolvedNodeCode()!=null)steps.add(new DTOs.PathStep(i++,d.getId(),d.getNode().getNodeCode(),d.getResolvedNodeCode(),d.getBranchType(),d.getImpactLevel(),d.getCreatedAt()));}return new DTOs.PathResponse(p.getId(),p.getPlayerTag(),p.getStatus(),p.getEndingCode(),p.getStartNodeCode(),p.getCurrentNode().getNodeCode(),steps);}
 public DTOs.PlaythroughResponse dto(Playthrough p){return new DTOs.PlaythroughResponse(p.getId(),p.getPlayerTag(),p.getUser().getEmail(),p.getStartNodeCode(),p.getCurrentNode().getNodeCode(),p.getLucidity(),p.getControlLevel(),p.getStatus(),p.getEndingCode(),p.getCreatedAt(),p.getUpdatedAt());}
}
