package com.utec.tropelcare.service;
import com.utec.tropelcare.dto.NotificationLogDto; import com.utec.tropelcare.entity.*; import com.utec.tropelcare.repository.*; import org.springframework.mail.SimpleMailMessage; import org.springframework.mail.javamail.JavaMailSender; import org.springframework.stereotype.Service; import java.time.Instant; import java.util.List;
@Service public class NotificationService{
 private final JavaMailSender mail; private final NotificationLogRepository logs; private final TropelSignalRepository signals;
 public NotificationService(JavaMailSender m,NotificationLogRepository l,TropelSignalRepository s){mail=m;logs=l;signals=s;}
 public void process(Long signalId){TropelSignal s=signals.findById(signalId).orElse(null);if(s==null)return;s.setStatus("PROCESANDO");s.setUpdatedAt(Instant.now());signals.save(s);String subject="[TROPELCARE] "+s.getSignalType()+" detectada en "+s.getTropel().getName()+" | Severidad "+s.getSeverity();try{SimpleMailMessage msg=new SimpleMailMessage();msg.setTo(s.getGuardian().getNotificationEmail());msg.setSubject(subject);msg.setText(body(s));mail.send(msg);s.setStatus("ATENDIDA");s.setUpdatedAt(Instant.now());signals.save(s);log(s,subject,"SENT",null,true);}catch(Exception e){s.setStatus("ERROR");s.setUpdatedAt(Instant.now());signals.save(s);log(s,subject,"FAILED",e.getMessage(),false);System.err.println("[TROPEL-LOG] Error SMTP: "+e.getMessage());}System.out.printf("[TROPEL-LOG] Signal ID: %d | Tropel: %s | Type: %s | Severity: %s | Unit: %s | Thread: %s | Status: %s%n",s.getId(),s.getTropel().getName(),s.getSignalType(),s.getSeverity(),s.getAssignedUnit(),Thread.currentThread().getName(),s.getStatus());}
 private void log(TropelSignal s,String subject,String status,String error,boolean sent){NotificationLog l=new NotificationLog();l.setSignal(s);l.setRecipientEmail(s.getGuardian().getNotificationEmail());l.setSubject(subject);l.setNotifStatus(status);l.setErrorMessage(error);l.setSentAt(sent?Instant.now():null);l.setCreatedAt(Instant.now());logs.save(l);}
 private String body(TropelSignal s){var t=s.getTropel();return "Hola "+s.getGuardian().getDisplayName()+",\n\nTu Tropel ha emitido una señal que requiere atención.\n\n"+"Señal ID         : #"+s.getId()+"\nTropel           : "+t.getName()+" ("+t.getSpecies()+")\nTipo de señal    : "+s.getSignalType()+"\nSeveridad        : "+s.getSeverity()+"\nUnidad asignada  : "+s.getAssignedUnit()+"\nAcción sugerida  : "+s.getRecommendedAction()+"\nEstado vital     : "+t.getVitalState()+"\nNivel de energía : "+t.getEnergyLevel()+"/100\nÍndice de caos   : "+t.getChaosIndex()+"/100\nEtapa mutación   : "+t.getMutationStage()+"/5\nRegistrada       : "+s.getCreatedAt()+"\n\nSeñal original:\n\""+s.getRawContent()+"\"\n\n— TropelCare Signal Engine, Tuckersoft";}
 @org.springframework.transaction.annotation.Transactional(readOnly=true) public List<NotificationLogDto> list(Long signalId){return logs.findBySignalIdOrderByCreatedAtDesc(signalId).stream().map(l->new NotificationLogDto(l.getId(),l.getSignal().getId(),l.getRecipientEmail(),l.getSubject(),l.getNotifStatus(),l.getErrorMessage(),l.getSentAt(),l.getCreatedAt())).toList();}
}
