package com.utec.tropelcare.service;

import com.utec.tropelcare.dto.SignalRequest; import com.utec.tropelcare.entity.*; import com.utec.tropelcare.repository.*; import org.junit.jupiter.api.*; import org.mockito.*; import org.springframework.context.ApplicationEventPublisher;
import java.time.Instant; import java.util.Optional; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;

class SignalServiceTest {
 @Mock TropelSignalRepository signals; @Mock TropelRepository tropels; @Mock SectorRepository sectors; @Mock GuardianRepository guardians; @Mock CareResponseRepository care; @Mock AiClassifierService ai; @Mock ApplicationEventPublisher publisher; @InjectMocks SignalService service;
 Guardian guardian; Sector sector; Tropel tropel;
 @BeforeEach void setUp(){MockitoAnnotations.openMocks(this);guardian=new Guardian();guardian.setId(1L);guardian.setDisplayName("Cameron Walker");guardian.setNotificationEmail("x@example.com");sector=new Sector();sector.setId(1L);sector.setSectorCode("SECTOR-7");sector.setCapacity(1);sector.setCurrentLoad(1);sector.setStabilityLevel(100);tropel=new Tropel();tropel.setId(1L);tropel.setName("BipBop");tropel.setSpecies("GLITCHY");tropel.setVitalState("ESTABLE");tropel.setEnergyLevel(80);tropel.setChaosIndex(10);tropel.setMutationStage(0);tropel.setGuardian(guardian);tropel.setSector(sector);when(tropels.findById(1L)).thenReturn(Optional.of(tropel));when(guardians.findById(1L)).thenReturn(Optional.of(guardian));when(signals.save(any())).thenAnswer(i->i.getArgument(0));}
 @Test void validJsonPersistsClassification(){when(ai.classify(anyString())).thenReturn(new AiClassifierService.Classification("HAMBRE","MODERADO","Laboratorio de Nutricion","Dar nutrientes",null));var out=service.create(new SignalRequest(1L,1L,"sensor","BipBop necesita comida urgentemente"));assertEquals("HAMBRE",out.signalType());assertEquals("MODERADO",out.severity());assertEquals("Laboratorio de Nutricion",out.assignedUnit());assertEquals("RECIBIDA",out.status());verify(publisher).publishEvent(any());}
 @Test void extraTextAroundJsonIsParsed(){var c=new AiClassifierService(new com.fasterxml.jackson.databind.ObjectMapper(),"http://localhost","","m");var result=c.parse("Aquí va: {\"signalType\":\"MUTACION\",\"severity\":\"GRAVE\",\"assignedUnit\":\"Division Genetica\",\"recommendedAction\":\"Aislar\"} fin");assertEquals("MUTACION",result.signalType());assertEquals("GRAVE",result.severity());}
 @Test void aiFailureUsesFallbackAndDoesNotPublish(){when(ai.classify(anyString())).thenThrow(new RuntimeException("timeout"));var out=service.create(new SignalRequest(1L,1L,"sensor","contenido de prueba suficientemente largo"));assertEquals("SENAL_CORRUPTA",out.signalType());assertEquals("LEVE",out.severity());assertEquals("ERROR",out.status());verify(publisher,never()).publishEvent(any());}
 @Test void criticalUpdatesStatsWithinLimits(){when(ai.classify(anyString())).thenReturn(new AiClassifierService.Classification("MUTACION","CRITICO","Division Genetica","Aislar",null));tropel.setChaosIndex(60);tropel.setMutationStage(5);service.create(new SignalRequest(1L,1L,"sensor","mutación crítica con brillo verde"));assertEquals(100,tropel.getChaosIndex());assertEquals(5,tropel.getMutationStage());assertEquals("CRITICO",tropel.getVitalState());}
 @Test void invalidJsonIsRejectedByParser(){var c=new AiClassifierService(new com.fasterxml.jackson.databind.ObjectMapper(),"http://localhost","","m");assertThrows(IllegalArgumentException.class,()->c.parse("{\"signalType\":\"NOPE\"}"));}
}
