services:
  postgres:
    image: postgres:16
    container_name: tropelcare-db
    environment:
      POSTGRES_DB: tropelcare
      POSTGRES_USER: tropeluser
      POSTGRES_PASSWORD: tropelpass
    ports:
      - "5432:5432"
    volumes:
      - tropelcare_pgdata:/var/lib/postgresql/data
volumes:
  tropelcare_pgdata:
